full-install release-install all clean release debug world dist-clean info :
	@cd ../vgnf;		make $@;	echo;echo

checkout:
	svn co http://dev-srv:8080/svn/SrcLib/vgnf/trunk ../vgnf

update diff:
	@cd ../vgnf;	svn $@;	echo;echo;