VERSION=0.3

full-install release-install all clean release debug world dist-clean info :
	cd ../vgnf;		make '$@';

checkout:
	svn co http://dev-srv:8080/svn/SrcLib/vgnf/trunk ../vgnf

update diff:
	cd ../vgnf;	svn '$@';

tags:
	# itself
	- svn mkdir http://dev-srv:8080/svn/SrcLib/vgnf/tags/ --message "Release $(VERSION)"
	svn copy http://dev-srv:8080/svn/SrcLib/vgnf/trunk http://dev-srv:8080/svn/SrcLib/vgnf/tags/tdvpm_$(VERSION) --message "Release $(VERSION)"
