SHELL=/bin/bash

checkout:
	svn co http://dev-srv:8080/svn/SrcLib/Virtuals/trunk ../Virtuals
	svn co http://dev-srv:8080/svn/SrcLib/vgDebug/trunk ../vgDebug
	svn co http://dev-srv:8080/svn/SrcLib/vgm/trunk ../vgm
	svn co http://dev-srv:8080/svn/SrcLib/vgd/trunk ../vgd
	svn co http://dev-srv:8080/svn/SrcLib/vgAlg/trunk ../vgAlg
	svn co http://dev-srv:8080/svn/SrcLib/vgTrian/trunk ../vgTrian
	svn co http://dev-srv:8080/svn/SrcLib/vge/trunk ../vge
	svn co http://svn.gna.org/svn/gle/gle/trunk ../gle
	svn co http://svn.gna.org/svn/gle/glo/trunk ../glo
	svn co http://dev-srv:8080/svn/SrcLib/vgeGL/trunk ../vgeGL
	svn co http://dev-srv:8080/svn/SrcLib/vgWX/trunk ../vgWX
	#svn co http://dev-srv:8080/svn/SrcLib/vgsdk/trunk vgsdk => already done (this makefile comes from vgsdk project).

full-install release-install dist-clean clean all:
	@### Core components ###
	@cd ../Virtuals;	make $@;	echo;echo
	@cd ../vgDebug;	make $@;	echo;echo
	@cd ../vgm;			make $@;	echo;echo
	@cd ../vgd;			make $@;	echo;echo
	@cd ../vgAlg;		make $@;	echo;echo
	@cd ../vgTrian;	make $@;	echo;echo
	@cd ../vge;			make $@;	echo;echo
	@cd ../gle;			make $@;	echo;echo
	@cd ../glo;			make $@;	echo;echo
	@cd ../vgeGL;		make $@;	echo;echo
	@cd ../vgWX;		make $@;	echo;echo
	@cd ../vgsdk;		make $@;	echo;echo