VERSION=0.3

full-install release-install all clean release debug world dist-clean info :
	cd ../vgBase;		make '$@';
	cd ../vgDebug;		make '$@';
	cd ../vgm;			make '$@';
	cd ../vgd;			make '$@';
	cd ../vgAlg;		make '$@';
	cd ../vgTrian;		make '$@';
	cd ../vge;			make '$@';
#	cd ../gle;			make '$@';
#	cd ../glo;			make '$@';
	cd ../vgeGL;		make '$@';
	cd ../vgWX;			make '$@';
	cd ../vgsdk;		make '$@';

checkout:
	svn co http://dev-srv:8080/svn/SrcLib/vgBase/trunk ../vgBase
	svn co http://dev-srv:8080/svn/SrcLib/vgDebug/trunk ../vgDebug
	svn co http://dev-srv:8080/svn/SrcLib/vgm/trunk ../vgm
	svn co http://dev-srv:8080/svn/SrcLib/vgd/trunk ../vgd
	svn co http://dev-srv:8080/svn/SrcLib/vgAlg/trunk ../vgAlg
	svn co http://dev-srv:8080/svn/SrcLib/vgTrian/trunk ../vgTrian
	svn co http://dev-srv:8080/svn/SrcLib/vge/trunk ../vge
#	svn co http://svn.gna.org/svn/gle/gle/trunk ../gle
#	svn co http://svn.gna.org/svn/gle/glo/trunk ../glo
	svn co http://dev-srv:8080/svn/SrcLib/vgeGL/trunk ../vgeGL
	svn co http://dev-srv:8080/svn/SrcLib/vgWX/trunk ../vgWX
	#svn co http://dev-srv:8080/svn/SrcLib/vgsdk/trunk vgsdk => already done (this makefile comes from vgsdk project).

update diff:
	cd ../vgBase;		svn '$@';
	cd ../vgDebug;		svn '$@';
	cd ../vgm;			svn '$@';
	cd ../vgd;			svn '$@';
	cd ../vgAlg;		svn '$@';
	cd ../vgTrian;		svn '$@';
	cd ../vge;			svn '$@';
#	cd ../gle;			svn '$@';
#	cd ../glo;			svn '$@';
	cd ../vgeGL;		svn '$@';
	cd ../vgWX;			svn '$@';
	cd ../vgsdk;		svn '$@';

tags:
	# itself
	- svn mkdir http://dev-srv:8080/svn/SrcLib/vgsdk/tags/ --message "Release $(VERSION)"
	svn copy http://dev-srv:8080/svn/SrcLib/vgsdk/trunk http://dev-srv:8080/svn/SrcLib/vgsdk/tags/tdvpm_$(VERSION) --message "Release $(VERSION)"
	# libs
	- svn mkdir http://dev-srv:8080/svn/SrcLib/vgBase/tags/ --message "Release $(VERSION)"
	svn copy http://dev-srv:8080/svn/SrcLib/vgBase/trunk http://dev-srv:8080/svn/SrcLib/vgBase/tags/tdvpm_$(VERSION) --message "Release $(VERSION)"
	- svn mkdir http://dev-srv:8080/svn/SrcLib/vgDebug/tags/ --message "Release $(VERSION)"
	svn copy http://dev-srv:8080/svn/SrcLib/vgDebug/trunk http://dev-srv:8080/svn/SrcLib/vgDebug/tags/tdvpm_$(VERSION) --message "Release $(VERSION)"
	- svn mkdir http://dev-srv:8080/svn/SrcLib/vgm/tags/ --message "Release $(VERSION)"
	svn copy http://dev-srv:8080/svn/SrcLib/vgm/trunk http://dev-srv:8080/svn/SrcLib/vgm/tags/tdvpm_$(VERSION) --message "Release $(VERSION)"
	- svn mkdir http://dev-srv:8080/svn/SrcLib/vgd/tags/ --message "Release $(VERSION)"
	svn copy http://dev-srv:8080/svn/SrcLib/vgd/trunk http://dev-srv:8080/svn/SrcLib/vgd/tags/tdvpm_$(VERSION) --message "Release $(VERSION)"
	- svn mkdir http://dev-srv:8080/svn/SrcLib/vgAlg/tags/ --message "Release $(VERSION)"
	svn copy http://dev-srv:8080/svn/SrcLib/vgAlg/trunk http://dev-srv:8080/svn/SrcLib/vgAlg/tags/tdvpm_$(VERSION) --message "Release $(VERSION)"	
	- svn mkdir http://dev-srv:8080/svn/SrcLib/vgTrian/tags/ --message "Release $(VERSION)"
	svn copy http://dev-srv:8080/svn/SrcLib/vgTrian/trunk http://dev-srv:8080/svn/SrcLib/vgTrian/tags/tdvpm_$(VERSION) --message "Release $(VERSION)"
	- svn mkdir http://dev-srv:8080/svn/SrcLib/vge/tags/ --message "Release $(VERSION)"
	svn copy http://dev-srv:8080/svn/SrcLib/vge/trunk http://dev-srv:8080/svn/SrcLib/vge/tags/tdvpm_$(VERSION) --message "Release $(VERSION)"
	- svn mkdir http://dev-srv:8080/svn/SrcLib/vgeGL/tags/ --message "Release $(VERSION)"
	svn copy http://dev-srv:8080/svn/SrcLib/vgeGL/trunk http://dev-srv:8080/svn/SrcLib/vgeGL/tags/tdvpm_$(VERSION) --message "Release $(VERSION)"
	- svn mkdir http://dev-srv:8080/svn/SrcLib/vgWX/tags/ --message "Release $(VERSION)"
	svn copy http://dev-srv:8080/svn/SrcLib/vgWX/trunk http://dev-srv:8080/svn/SrcLib/vgWX/tags/tdvpm_$(VERSION) --message "Release $(VERSION)"	
